FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps --omit=dev --ignore-scripts

FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=5027
COPY package.json package-lock.json ./
COPY --from=deps /app/node_modules ./node_modules
COPY build ./build
COPY build/client ./public
EXPOSE 5027
CMD ["npm", "run", "start"]
